{
  "title": "Spur Gear Design",
  "description": "CADQuery pseudocode for generating a spur gear with 24 teeth, 60mm pitch diameter, and 5mm bore.",
  "imports_needed": [
    "cadquery as cq"
  ],
  "global_variables": {
    "tolerance": "0.05",
    "units": "mm"
  },
  "initialization": "CREATE workplane on XY plane\nSET tolerance = 0.05\nINITIALIZE coordinate system",
  "main_blocks": [
    {
      "step_number": 1,
      "operation_type": "create_pitch_circle",
      "pseudocode": "CREATE circle with radius=30 on workplane\nASSIGN result to variable 'pitch_circle'",
      "variables_used": [
        "pitch_circle",
        "workplane"
      ],
      "dependencies": [],
      "comments": "Creates the base circle for the gear"
    },
    {
      "step_number": 2,
      "operation_type": "extrude_gear_blank",
      "pseudocode": "EXTRUDE 'pitch_circle' with distance=8\nASSIGN result to variable 'gear_blank'",
      "variables_used": [
        "gear_blank",
        "pitch_circle"
      ],
      "dependencies": [
        1
      ],
      "comments": "Creates the 3D gear blank"
    },
    {
      "step_number": 3,
      "operation_type": "create_bore_hole_circle",
      "pseudocode": "CREATE circle with radius=2.5 on workplane\nASSIGN result to variable 'bore_hole_circle'",
      "variables_used": [
        "bore_hole_circle",
        "workplane"
      ],
      "dependencies": [],
      "comments": "Creates the circle for the bore hole"
    },
    {
      "step_number": 4,
      "operation_type": "cut_bore_hole",
      "pseudocode": "CUT 'bore_hole_circle' from 'gear_blank'\nASSIGN result to variable 'gear_with_bore'",
      "variables_used": [
        "gear_with_bore",
        "gear_blank",
        "bore_hole_circle"
      ],
      "dependencies": [
        2,
        3
      ],
      "comments": "Cuts the bore hole through the gear blank"
    },
    {
      "step_number": 5,
      "operation_type": "create_gear_profile",
      "pseudocode": "CREATE involute gear profile with number_of_teeth=24, module=2.5, pressure_angle=20\nPOSITION profile on 'gear_blank'\nASSIGN result to variable 'gear_profile'",
      "variables_used": [
        "gear_profile",
        "gear_blank"
      ],
      "dependencies": [
        2
      ],
      "comments": "Generates the involute gear tooth profile"
    },
    {
      "step_number": 6,
      "operation_type": "cut_gear_teeth",
      "pseudocode": "CUT 'gear_profile' from 'gear_with_bore'\nASSIGN result to variable 'gear_with_teeth'",
      "variables_used": [
        "gear_with_teeth",
        "gear_with_bore",
        "gear_profile"
      ],
      "dependencies": [
        4,
        5
      ],
      "comments": "Cuts the gear teeth into the gear blank"
    },
    {
      "step_number": 7,
      "operation_type": "chamfer_edges",
      "pseudocode": "SELECT outer edges of 'gear_with_teeth'\nAPPLY fillet with radius=0.5 to selected edges\nASSIGN result to variable 'final_gear'",
      "variables_used": [
        "final_gear",
        "gear_with_teeth"
      ],
      "dependencies": [
        6
      ],
      "comments": "Applies a chamfer to the outer edges"
    }
  ],
  "finalization": "EXPORT 'final_gear' to STEP format\nSAVE to output file\nCLEANUP temporary variables",
  "estimated_lines": 35
}