# Spur Gear Design
# Detailed CAD plan for creating a spur gear with 24 teeth, a pitch diameter of 60mm, and a 5mm bore hole, suitable for 3D printing or CNC milling.

# Imports
import cadquery as cq

# Constants
pitch_diameter = 60.0
gear_thickness = 8.0
bore_radius = 2.5
number_of_teeth = 24
module = 2.5
pressure_angle = 20
chamfer_radius = 0.5
pitch_circle_radius = 30

# Main Construction
result = cq.Workplane('XY')

# Step 1: Create a circular sketch representing the pitch circle of the gear.
result = result.circle(radius=30)

# Step 2: Extrude the pitch circle sketch to create the gear blank with a face width of 8mm.
result = result.extrude(distance=8)

# Step 3: Create a circular sketch for the bore hole at the center of the gear.
bore_circle = bore_circle.circle(radius=2.5)

# Step 4: Cut the bore hole through the gear blank.
result = result.cut()

# Step 5: Create the involute gear profile using the specified parameters. Module is calculated as pitch diameter / number of teeth (60/24 = 2.5).
gear_profile = gear_profile.involuteGear(number_of_teeth=24, module=2.5, pressure_angle=20)

# Step 6: Cut the gear teeth into the gear blank using the generated involute profile.
result = result.cut()

# Step 7: Apply a 0.5mm chamfer to the outer edges of the gear to remove sharp edges.
result = result.fillet(radius=0.5)

